### ISSUE TITLE
How to disable default layout?

### ISSUE THREAD

**Issue by bigbn** [cashbit/sails-crudface#1]
I want to get my forms without main container(load them dynamicaly via JSON), 
i mean thing like this:

``` javascript
res.view('home/login', {layout: null});
```

how can i set "layout = null" for all forms without modifing crudface package files? Or maybe, how can i extend my controller to do that?

**Comment by bigbn** [comment]
i'm not find the solution, so i temporary change the index.js by this way:

``` javascript
    'new' : function(req,res,next){
      module.exports.createView(req,res,next,controller,function(viewConfig){
        if (req.isAjax) viewConfig.layout = null;
        res.view(viewConfig);
      });
    },
```

**Comment by cashbit** [comment]
I think you can re-declare the 'new' function in the controller after the "init", overriding the existent new function in the index.js, maintaining compatibility with future versions...

**Comment by bigbn** [comment]
yes, this only right way for now.
