### ISSUE TITLE
Field-Types?

### ISSUE THREAD

**Issue by spencerthayer** [cashbit/sails-crudface#10]
https://github.com/cashbit/sails-crudface/blob/master/components/_crud/edit.ejs

I noticed you have some amazing functionality here like <% if (field.type == 'checkbox') { %> but I am curious, where does this get defined? From what I can tell Sails only allows rudimentary types in the JSON DB. Is there something I am missing?

**Comment by cashbit** [comment]
There isn't a one-to-one correspondence between sails-crudface field types and the salsjs models field types.
Simply, the checkbox will store a boolean in the model, accordingly the model definition.
