### ISSUE TITLE
missing views/fileuploads/attachments.ejs

### ISSUE THREAD

**Issue by angleman** [cashbit/sails-crudface#2]
Sweet project!

Able to `index` via `http://localhost:1337/contact/`
Also able to  `new` via `http://localhost:1337/contact/new`, except I get the following error:

``` js
{
  "status": 500,
  "errors": [
    "ENOENT, no such file or directory '.../views/fileuploads/attachments.ejs'"
  ]
}
```

After pressing `Create Contact` button or if I try to `show` the contact via `http://localhost:1337/contact/show/1`.  The new contact does correctly show up on the `index` page `http://localhost:1337/contact/`

Note `edit` via `http://localhost:1337/contact/edit/1` looks correct and produces the same error when the `Save` button is pressed.

Thoughts?

**Comment by derekbasch** [comment]
@angleman there is supposed to be a drag and drop file upload area on the show page. It looks like @cashbit  forgot to include the ejs template for the upload area. Disable the upload feature until he fixes it.
- Create an empty file 
  
  ```
  touch /views/contact/fileuploads/attachments.ejs
  ```
- Disable the upload feature:
  
  ```
  /api/controllers/contact/ContactCrudConfig.js
  
  {
      "prettyName"  : "Contact",
      "showAttachments" : false,
      "attachmentIsPublic": false,
      ......
  ```

**Comment by angleman** [comment]
@derekbasch sounds like the right kind of idea. I gave it a try but I'm getting the same error. Do you know if this is tied to FileuploadsController.js? If so, maybe we can disable it. What do you think?

**Comment by cashbit** [comment]
Hi all,
in the next days i'll fix the problem.
ciao

**Comment by angleman** [comment]
@cashbit, that would be great :-)

**Comment by cashbit** [comment]
fixed (i hope, no time to test now, sorry).
let me know.

**Comment by angleman** [comment]
moved it to `views/fileuploads/` and it worked! thanks :smile:
