### ISSUE TITLE
ReferenceError: Fileuploads is not defined

### ISSUE THREAD

**Issue by Globegitter** [cashbit/sails-crudface#3]
I really love the idea of this plugin, I think it is really necessary to make sailsjs even more awesome and productive and this is a great start.
Anyway, I just wanted to try it out without any fileupload, e.g. for a `Video` model and when I go to `http://localhost:1337/video/show/1` I get the error:
`Internal Server Error - ReferenceError: Fileuploads is not defined`

**Comment by cashbit** [comment]
In the latest versions this bug is fixed. Le me know if ok.
