### ISSUE TITLE
Default CrudConfig file

### ISSUE THREAD

**Issue by Globegitter** [cashbit/sails-crudface#4]
I would love to see this great project getting improved and improved and would be willing to contribute myself if you can give me some hints on where to start.
Anyway, it would be great to not necessarily need to create a `xCrudConfig.js` for each model and sort of have a 'default' if that file does not exist. Most easily it would be to just take all the attributes from the model and have them as a normal text-input or a bit of a more clever approach of deciding based on the attribute type.

**Comment by cashbit** [comment]
It's a great idea, you can do this by overriding the loadConfig function, introducing in that point a routine that do the trick.
