### ISSUE TITLE
Removing bootstrap form helpers as dependency

### ISSUE THREAD

**Issue by Globegitter** [cashbit/sails-crudface#5]
It would be great if instead of this plugin pack only plugins available from bower could be used. That would slightly increase the productivity, especially when using it in combination with https://github.com/smies/sails-generate-bower and will probably also help if automation is a goal in the future.

If you give me a list of things what exactly you are using from this plugin I could look for some suitable replacements, if you agree.

**Comment by cashbit** [comment]
The only thing i remember is bootstrap form helpers and the bootstrap css.
All other things are in salsjs framework.
