### ISSUE TITLE
Creating a generator to automate the steps

### ISSUE THREAD

**Issue by Globegitter** [cashbit/sails-crudface#6]
I don't know if you have looked at all in the new sails-generators and I haven't myself yet, but it would be great that automatically generates the views for you.
Right now (sails 0.10.x) the usage is `sails generate api model`, maybe you could have three commands:
`sails generate crud` which does all the setup, copying the `_crud.js` to the `js` folder as well as the `_crud` folder to the `view` (`_crudtemplates` shouldn't be needed anymore I think with the next two generators)
`sails generate crud model` which generate a model, controller, crudconfig and the views.
`sails generate crud-views model` which just generates the views.

Just let me know what you think and maybe I could also help out somewhere. Thanks for all the work you have put into this so far.

**Comment by Jogai** [comment]
Its already planned I think, see https://github.com/cashbit/sails-crudface/edit/master/README.md#L94

**Comment by tjwebb** [comment]
+1

**Comment by cashbit** [comment]
Sorry, it's planned, but lack of time.
