### ISSUE TITLE
Displaying all Models - UI improvements

### ISSUE THREAD

**Issue by Globegitter** [cashbit/sails-crudface#7]
I do like the default ui, but it is only showing two attributes of my model and it would be great to see more, or in an ideal world all, but that makes the design a bit more complicated of course.
Anyway, some simple ideas to just show one or two more attributes would be to put the buttons all into one columns, to get some more space for other columns.
Also you could make the rows themselves clickables and remove the 'Show' button.

Just throwing out some ideas, feel free to take or ignore whatever you want and again, would over my help as well.

**Comment by Jogai** [comment]
You can configure the visibility of your model attributes with the "ines" attribute. See https://github.com/cashbit/sails-crudface#who-is-ines-

**Comment by Globegitter** [comment]
@Jogai Aaahhh thanks, that was bad reading on my part. Will test that out again.
