### ISSUE TITLE
Using sails-crudface as admin backend in addition to JSON response

### ISSUE THREAD

**Issue by Globegitter** [cashbit/sails-crudface#8]
This is more of an idea and I haven't fully fledged it out in my head yet (just got started with sails a few days ago), but I though I am writing the idea down for now:
I want to use the default sails configuration/convention and be able to serve an API (the JSON response), ideally with a `/api/v1/` prefix
And then I would love to use sails-crudface to use my already defined models and serve the admin ui under a `/admin/` prefix.
So let's say I have my `Video` model then I would access:
`localhost:1337/api/v1/videos/`to get the default JSON response
`localhost:1337/admin/videos/` having it login-secured and then seeing the ui that sails-crudface provides.
I will obviously spend some time myself looking into it once I have a better understanding of sails but maybe you have some ideas.

**Comment by sauloonze** [comment]
Did you find any solution to do it?

**Comment by Globegitter** [comment]
@sauloonze Other projects came into the way, so out of time shortage for the project in question I decided to go with keystone.js. Once I have more time (and also used more sails) I'll hopefully be able to look into that again.
