### ISSUE TITLE
Issue on sails 0.10 rc11

### ISSUE THREAD

**Issue by rvgrinsven** [cashbit/sails-crudface#9]
Problem seems to be controller.exports doesn't contain fieldsConfig (anymore?). 

It errors on index.js:846 with can't take length of undefined.

**Comment by cashbit** [comment]
fieldsConfig it's a sails-crudface requirement. 
Never defined in the main salsjs code.
You can find more here: https://github.com/cashbit/sails-crudface/wiki/Crud-configuration-file-specifications

**Comment by rvgrinsven** [comment]
Thanks a lot. Sorry for cluttering this but google didnt yield anything.
